name: momentum
description: "Pomodoro app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase and Authentication
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  google_sign_in: ^6.2.1
  firebase_storage: ^12.1.0

  # State Management & Utilities
  provider: ^6.1.2
  confetti: ^0.7.0
  fl_chart: ^0.68.0
  iconsax: ^0.0.8
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_local_notifications: ^17.2.1
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_background.gif
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # Your project's min SDK
  adaptive_icon_background: "#000000"
