// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT5fMB3WemQyLa46fEw5r0BX5m4BatLYI',
    appId: '1:67533312236:android:8cfdecdd517764d61095c9',
    messagingSenderId: '67533312236',
    projectId: 'fish-ultimate-productivity',
    databaseURL: 'https://fish-ultimate-productivity-default-rtdb.firebaseio.com',
    storageBucket: 'fish-ultimate-productivity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzUoryJjbmz4_pvtBnqxGIlNfEHCjI7fM',
    appId: '1:67533312236:ios:8d91f2ef2b18efc61095c9',
    messagingSenderId: '67533312236',
    projectId: 'fish-ultimate-productivity',
    databaseURL: 'https://fish-ultimate-productivity-default-rtdb.firebaseio.com',
    storageBucket: 'fish-ultimate-productivity.firebasestorage.app',
    androidClientId: '67533312236-3egd8mnjk6glnahiv9ebchd4nkv5ktgp.apps.googleusercontent.com',
    iosClientId: '67533312236-kr1h6s7r7qv2gdchou5lj2bk19mmaogh.apps.googleusercontent.com',
    iosBundleId: 'com.twoman.momentum.momentum',
  );
}
